### ISSUE TITLE
New Proton.js

### ISSUE THREAD

**Issue by JPeer264** [a-jie/three.proton#1]
Awesome work! 

Is this now the new Proton.js?

**Comment by a-jie** [comment]
no. It is based on Proton, which is a 3d particle engine using three.js.

Completely not a new proton

**Comment by a-jie** [comment]
You can view example directly

**Comment by JPeer264** [comment]
Wow, it's actually easier that in proton js :)

so, where should I focus on my documentation? two big libraries are a bit too much for me right now - I guess we should focus on that one?

**Comment by a-jie** [comment]
I prefer Proton. it can adapt to a variety of projects. three.proton is a good 3d engine.

**Comment by JPeer264** [comment]
perfekt ;)
