### ISSUE TITLE
Typo on line 3293

### ISSUE THREAD

**Issue by Jasdoge** [a-jie/three.proton#12]
https://github.com/a-jie/three.proton/blob/7630aa15068c8e2dda29de89774ef24eeb1d76ac/build/three.proton.js#L3287

var the should be var tha. Causing an error when using SphereZone

**Comment by a-jie** [comment]
Thank you very much, cool.

**Comment by a-jie** [comment]
Your question has been fixed, I am very sorry that I was doing some work related to flutter some time ago.
