### ISSUE TITLE
RequireJS / Modules support

### ISSUE THREAD

**Issue by IceReaper** [a-jie/three.proton#2]
I've currently added `define(['./three'], function (THREE) {` on top, and `return Proton; });` at the end of the file, also commented out the outer closure wrapping window and the `window.Proton = Proton;` to get this to work as a workaround.

**Comment by a-jie** [comment]
Thank you very much, I have added the commonjs amd mode support.
Examples in https://github.com/a-jie/three.proton/blob/master/example/meshzone.html
