### ISSUE TITLE
Removing proton instance from scene

### ISSUE THREAD

**Issue by nbasili** [a-jie/three.proton#3]
What is the proper way to remove a proton instance (along with all its emitters) from a THREE.js scene, so that all existing particles will be removed from the scene object as well?

Will 

```
// create proton instance
var proton = new Proton();
....
// add it to scene
proton.addRender(new Proton.MeshRender(scene));
....
....
// remove it from scene
proton.destroy();
``` 

do the job?

Btw, proton.destroy() crashes on ```this.particlePool.destroy();```. The ```particlePool``` is undefined and looking at the code, it is not set anywhere.

**Comment by a-jie** [comment]
This is indeed a bug, I have to fix it, thank you very much!

However, if you want to delete the particles, please call emitter.destroy.
proton.destroy method will stop rendering at the same time.

**Comment by nbasili** [comment]
Thank you
